---
DISABLE_LINTERS:
  - BASH_EXEC
  - COPYPASTE_JSCPD
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - SPELL_CSPELL
  - YAML_PRETTIER
EXCLUDED_DIRECTORIES:
  - ".git"
  - ".venv"
PYTHON_BANDIT_CONFIG_FILE: .github/linters/bandit.yml
PYTHON_BLACK_CONFIG_FILE: .github/linters/python_black.toml
PYTHON_FLAKE8_CONFIG_FILE: .github/linters/flake8.cfg
PYTHON_ISORT_CONFIG_FILE: .github/linters/isort.cfg
PYTHON_PYLINT_ARGUMENTS: --disable=E0401,E0606
PYTHON_PYRIGHT_CONFIG_FILE: .github/linters/pyrightconfig.json
PYTHON_RUFF_CONFIG_FILE: .github/linters/ruff.toml
REPORT_OUTPUT_FOLDER: none
REPOSITORY_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
SHOW_SKIPPED_LINTERS: true
